language: node_js
sudo: false

os: linux

env:
  global:
    - NODE_VERSION=10

before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm@6 && node -v && npm -v

install:
  - npm ci

script:
  - npm run lib:prod
  - npm test
  - npm run docs:build

#deploy:
#  provider: npm
#  email: "tomas.dostal@kpsys.cz"
#  api_key: $NPM_TOKEN
#  skip_cleanup: true
#  on:
#    branch: master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local_dir: "dist/docs"
  on:
    branch: master